### ISSUE TITLE
Country Enum not exposed in Library

### ISSUE THREAD

**Issue by RobertDeRose** [Vantiv/vantiv-sdk-for-python#1]
Should this not be exposed through the Library?

https://github.com/Vantiv/vantiv-sdk-for-python/blob/92212838383f2aab616acea6732fcdea866baf84/schema/litleCommon_v11.1.xsd#L243

Seems like it should be, or else we have to create our own.

**Comment by Houzl** [comment]
<xs:simpleType name="countryTypeEnum">
        <xs:restriction base="xs:string">

Although countryTypeEnum is named as Enum, it is still a string. We are using the enumerations to valid your input string on the server side. The value is the abbreviation of a country name. You do not need to create a Enum for this. You just need to set the string of the abbreviation of a country name as the value of the element whose type is countryTypeEnum.

The country names corresponding to the abbreviations can be found in the ISO 3166-1 standard.
All Country Codes are 2-character except for the United States, which accepts both US and USA.

**Comment by RobertDeRose** [comment]
OK, so the list in the Schema is no different than what the ISO standard list.  So if we wanted to do pre-validation from user input, we can rely on something like `pycountry` which is a wrapper around the ISO 3166-1 database?  Or are there countries not in your list that are in the Standard?  It was assumed that we needed this on our side to ensure we only take payment from Countries you supported.

**Comment by VantivSDK** [comment]
Hi @RobertDeRose,
Correct the schema is inline with the ISO spec (plus the inclusion of USA in our XSD), so you should be able to use a library implementation of that spec for validation on you side. If you don't perform validation on this field, our system would respond with a system error and the specific schema violation as the message.
